function [fitresult, gof] = fourier_fir(tt, yy,show)
%CREATEFIT(TT,YY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: tt
%      Y Output: yy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Dec-2022 23:25:43


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tt, yy );

% Set up fittype and options.
ft = fittype( 'fourier4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0.438776744336814];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if show == true
    % Plot fit with data.
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, xData, yData );
    legend( h, 'yy vs. tt', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'tt', 'Interpreter', 'none' );
    ylabel( 'yy', 'Interpreter', 'none' );
    grid on
end


